version: 0.0
os: linux
files:
  - source: /backend
    destination: /var/www/cloudpath/backend
  - source: /frontend/dist
    destination: /var/www/cloudpath/frontend/dist
  - source: /scripts
    destination: /var/www/cloudpath/scripts
hooks:
  ApplicationStop:
    - location: scripts/stop_server.sh
      timeout: 300
      runas: ec2-user
  BeforeInstall:
    - location: scripts/install_dependencies.sh
      timeout: 300
      runas: root
  ApplicationStart:
    - location: scripts/start_server.sh
      timeout: 300
      runas: root
